### ISSUE TITLE
Point_to_object

### ISSUE THREAD

**Issue by adonini** [HESOFTS/Divergent-Pointing#1]
Remind me @vuillaut why we defined this function in `telescope.py`
```
    def point_to_object(self, object):
        """
        Point to object.

        Parameters
        ----------
        object: numpy.array([x, y, z])
        """
        GT = np.sqrt(((self.position - object) ** 2).sum())
        alt_tel = np.arcsin((-self.z.value + object[2]) / GT)
        az_tel = np.arctan2((- self.y.value + object[1]), (- self.x.value + object[0]))
        self.point_to_altaz(alt_tel * u.rad, az_tel * u.rad)
```

Is this supposed to be the real pointing to an object in the sky?

**Comment by vuillaut** [comment]
Hi.
This function can be used to point to a point (object) in space rather than a direction in the sky.
It can be used for convergent or divergent pointing to point all telescopes to a point in space (<=> intersection of the pointing directions).
